"""Reconciliation domain layer."""
from app.modules.reconciliation.domain.entities import (
    IdentificationStatus,
    EvidenceType,
    SignalStrength,
    EvidenceSignal,
    CustomerMatchCandidate,
    CustomerIdentificationResult,
)
from app.modules.reconciliation.domain.normalizer import PayerStringNormalizer
from app.modules.reconciliation.domain.payment_intake import (
    PaymentIntakeReasonCode,
    PaymentIntakeResult,
    PaymentIntakeStatus,
    PaymentIntakeRuleEngine,
)
from app.modules.reconciliation.domain.candidate_filters import (
    CandidateFilterCriteria,
    CandidateFilterRuleEngine,
    ExcludedCandidateInvoice,
    FilterExclusionReason,
    FilteredCandidateUniverse,
)
from app.modules.reconciliation.domain.candidate_invoices import (
    CandidateInvoice,
    CandidateInvoiceEvidenceSignal,
    CandidateInvoiceUniverse,
    InvoiceEvidenceType,
)
from app.modules.reconciliation.domain.invoice_rules import (
    CandidateInvoiceRuleEngine,
    InvoiceCandidateContext,
)
from app.modules.reconciliation.domain.rules import PayerIdentificationRuleEngine

from app.modules.reconciliation.domain.exact_matching import (
    ExactMatchCriteria,
    ExactMatchEvidenceSignal,
    ExactMatchEvidenceType,
    ExactMatchHypothesis,
    ExactMatchReasonCode,
    ExactMatchResult,
    ExactMatchRuleEngine,
    ExactMatchStatus,
)

from app.modules.reconciliation.domain.partial_matching import (
    PartialMatchCriteria,
    PartialMatchEvidenceSignal,
    PartialMatchEvidenceType,
    PartialMatchHypothesis,
    PartialMatchReasonCode,
    PartialMatchResult,
    PartialMatchRuleEngine,
    PartialMatchStatus,
)

from app.modules.reconciliation.domain.multi_invoice_matching import (
    MultiInvoiceMatchCriteria,
    MultiInvoiceMatchEvidenceSignal,
    MultiInvoiceMatchEvidenceType,
    MultiInvoiceMatchHypothesis,
    MultiInvoiceMatchReasonCode,
    MultiInvoiceMatchResult,
    MultiInvoiceMatchRuleEngine,
    MultiInvoiceMatchStatus,
)
from app.modules.reconciliation.domain.combination_matching import (
    CombinationHypothesis,
    CombinationMatchCriteria,
    CombinationMatchEvidenceSignal,
    CombinationMatchEvidenceType,
    CombinationMatchReasonCode,
    CombinationMatchResult,
    CombinationMatchRuleEngine,
    CombinationMatchStatus,
)
from app.modules.reconciliation.domain.evidence_normalization import (
    CanonicalEvidenceObject,
    EvidenceNormalizationEngine,
    EvidenceNormalizationResult,
    NormalizedCandidateBundle,
    NormalizedEvidenceResult,
    NormalizedEvidenceSource,
    NormalizedEvidenceStrength,
    NormalizedEvidenceType,
    NormalizedPaymentEvidenceContext,
    NormalizedRelevantIdentifiers,
    NormalizedTargetEntity,
)
from app.modules.reconciliation.domain.matching_scoring import (
    DEFAULT_SCORING_WEIGHTS,
    CandidateScoreResult,
    MatchingScoringEngine,
    MatchingScoringResult,
    ScoreContribution,
    ScoringSignalType,
    ScoringWeightsConfig,
)

__all__ = [
    "IdentificationStatus",
    "EvidenceType",
    "SignalStrength",
    "EvidenceSignal",
    "CustomerMatchCandidate",
    "CustomerIdentificationResult",
    "PayerStringNormalizer",
    "PayerIdentificationRuleEngine",
    "PaymentIntakeStatus",
    "PaymentIntakeReasonCode",
    "PaymentIntakeResult",
    "PaymentIntakeRuleEngine",
    "CandidateInvoice",
    "CandidateInvoiceEvidenceSignal",
    "CandidateInvoiceUniverse",
    "InvoiceEvidenceType",
    "CandidateInvoiceRuleEngine",
    "InvoiceCandidateContext",
    "FilterExclusionReason",
    "CandidateFilterCriteria",
    "ExcludedCandidateInvoice",
    "FilteredCandidateUniverse",
    "CandidateFilterRuleEngine",
    "ExactMatchStatus",
    "ExactMatchReasonCode",
    "ExactMatchEvidenceType",
    "ExactMatchEvidenceSignal",
    "ExactMatchCriteria",
    "ExactMatchHypothesis",
    "ExactMatchResult",
    "ExactMatchRuleEngine",
    "PartialMatchStatus",
    "PartialMatchReasonCode",
    "PartialMatchEvidenceType",
    "PartialMatchEvidenceSignal",
    "PartialMatchCriteria",
    "PartialMatchHypothesis",
    "PartialMatchResult",
    "PartialMatchRuleEngine",
    "MultiInvoiceMatchStatus",
    "MultiInvoiceMatchReasonCode",
    "MultiInvoiceMatchEvidenceType",
    "MultiInvoiceMatchEvidenceSignal",
    "MultiInvoiceMatchCriteria",
    "MultiInvoiceMatchHypothesis",
    "MultiInvoiceMatchResult",
    "MultiInvoiceMatchRuleEngine",
    "CombinationMatchStatus",
    "CombinationMatchReasonCode",
    "CombinationMatchEvidenceType",
    "CombinationMatchEvidenceSignal",
    "CombinationMatchCriteria",
    "CombinationHypothesis",
    "CombinationMatchResult",
    "CombinationMatchRuleEngine",
    # Phase 14.10 Evidence Normalization
    "NormalizedEvidenceType",
    "NormalizedEvidenceSource",
    "NormalizedEvidenceResult",
    "NormalizedEvidenceStrength",
    "NormalizedTargetEntity",
    "NormalizedRelevantIdentifiers",
    "CanonicalEvidenceObject",
    "NormalizedCandidateBundle",
    "NormalizedPaymentEvidenceContext",
    "EvidenceNormalizationResult",
    "EvidenceNormalizationEngine",
    # Phase 14.11 Matching & Scoring
    "ScoringSignalType",
    "ScoringWeightsConfig",
    "ScoreContribution",
    "CandidateScoreResult",
    "MatchingScoringResult",
    "MatchingScoringEngine",
    "DEFAULT_SCORING_WEIGHTS",
]

