"""Banking transaction stopwords, payment aggregator handles, and legal suffixes."""

from typing import Dict, Set

# Generic banking keywords, rail codes, transaction descriptors, and institutions.
# These words must NOT be treated as distinct customer identity tokens.
BANKING_GENERIC_STOPWORDS: Set[str] = {
    # Payment rails and transfer types
    "neft",
    "rtgs",
    "imps",
    "upi",
    "ach",
    "nach",
    "ecs",
    "pos",
    "atm",
    "cms",
    "ift",
    "tfr",
    "trf",
    "clg",
    "chq",
    "cheque",
    "dd",
    "wire",
    "swift",
    "ft",
    "funds",
    "transfer",
    "remittance",
    "settlement",
    # Transaction descriptors
    "payment",
    "pyd",
    "pymt",
    "pay",
    "received",
    "rcvd",
    "credit",
    "cr",
    "deposit",
    "dep",
    "debit",
    "dr",
    "withdrawal",
    "wdl",
    "refund",
    "chargeback",
    "fee",
    "charges",
    "interest",
    "tax",
    "gst",
    "tds",
    "cash",
    "online",
    "auto",
    "mandate",
    "drfee",
    "crfee",
    # Banking identifiers and generic terms
    "bank",
    "bnk",
    "sbi",
    "hdfc",
    "icici",
    "axis",
    "pnb",
    "bob",
    "kotak",
    "yes",
    "idbi",
    "canara",
    "union",
    "indusind",
    "rbi",
    "branch",
    "acc",
    "acct",
    "account",
    "no",
    "num",
    "ref",
    "reference",
    "utr",
    "urn",
    "id",
    "txn",
    "trans",
    "transaction",
    "bill",
    "inv",
    "invoice",
    "to",
    "by",
    "from",
    "for",
    "in",
    "on",
    "at",
    "via",
    "through",
    "with",
    # Payment aggregators and gateways
    "rzp",
    "razorpay",
    "paytm",
    "phonepe",
    "gpay",
    "googlepay",
    "bharatpe",
    "cashfree",
    "billdesk",
    "ccavenue",
    "pinelabs",
    "instamojo",
    "stripe",
    "payu",
}

# Known payment aggregator VPA handles.
# A VPA whose user prefix is an aggregator ID cannot reliably identify an individual customer without merchant context.
PAYMENT_AGGREGATOR_VPAS: Set[str] = {
    "razorpay",
    "paytm",
    "phonepe",
    "axisbank",
    "okhdfcbank",
    "okaxis",
    "okicici",
    "oksbi",
    "ybl",
    "ibl",
    "axl",
    "apl",
    "cashfree",
    "billdesk",
    "bharatpe",
    "cred",
}

# Corporate legal structure designators.
# Key is normalized designator; value is canonical normalized representation.
# NOTE: Distinct industry nouns like 'industries', 'chemicals', 'enterprises', 'holding'
# are deliberately NOT included here so they are NEVER falsely collapsed.
CORPORATE_LEGAL_SUFFIXES: Dict[str, str] = {
    "pvt ltd": "private limited",
    "p ltd": "private limited",
    "private ltd": "private limited",
    "pvt limited": "private limited",
    "private limited": "private limited",
    "ltd": "limited",
    "limited": "limited",
    "inc": "incorporated",
    "incorporated": "incorporated",
    "corp": "corporation",
    "corporation": "corporation",
    "llc": "limited liability company",
    "llp": "limited liability partnership",
    "gmbh": "gmbh",
    "sa": "sa",
    "co": "company",
    "company": "company",
}
